##########################################################################################################################

# File automatically-generated by tool: [projectgenerator] version: [4.5.0-RC5] date: [Wed Jul 09 15:19:59 HKT 2025] 

##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = RM2025-PowerControlBoard


######################################
# building variables
######################################

# debug option
#-g0	no debug information
#-g1	minimal debug information
#-g		default debug information
#-g3	maximal debug information
DEBUG = -g3

# optimization
# -O0 		no optimization
# -O1 		
# -O2
# -O3
# -Os 		optimize for size
# -Ofast 	optimize for speed
# -Og 		optimize for debugging
OPT = -Ofast

# silent mode
VERBOSE = 0

# C standard
CSTD = -std=gnu11

# C++ standard
CPPSTD = -std=gnu++14

#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

CORE_DIR = 

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/adc.c \
Core/Src/fdcan.c \
Core/Src/tim.c \
Core/Src/stm32g4xx_it.c \
Core/Src/stm32g4xx_hal_msp.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_hrtim.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c \
Core/Src/system_stm32g4xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/hrtim.c \
Core/Src/dma.c \
Core/Src/comp.c \
Core/Src/opamp.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_comp.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp_ex.c \
Core/Src/dac.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dac.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dac_ex.c

# CPP sources
CPP_SOURCES =  \
$(wildcard Core/Src/*.cpp)

# CPP compiled
CPP_COMPILED = 

# ASM sources
ASM_SOURCES =  \
startup_stm32g474xx.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32G474xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32G4xx_HAL_Driver/Inc \
-IDrivers/STM32G4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32G4xx/Include \
-IDrivers/CMSIS/Include


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = stm32g474rbtx_flash.ld
LDSCRIPT = stm32g474rbtx_flash.ld

include SuperCap.mk

# *** EOF ***
